<?php

/**
 * @file
 * Allows users to delete configuration items from the UI.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function config_delete_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'config_delete_form') {
    unset($form['export']);

    $form['submit'] = [
      '#type' => 'submit',
      '#value' => t('Delete'),
    ];
  }
}
