config_delete.delete:
  path: '/admin/config/development/configuration/delete'
  defaults:
    _form: '\Drupal\config_delete\Form\ConfigDeleteForm'
    _title: 'Delete'
  requirements:
    _permission: 'delete configuration'
