<?php

/**
 * @file
 * Delete configuration items from the UI.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function config_delete_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'config_delete_form') {
    unset($form['export']);

    $form['config_delete_notice'] = [
      '#type' => 'markup',
      '#markup' => t('Notice: Deleting configuration items can potentially break your site. Please use this only if you know what are you doing.'),
      '#prefix' => '<strong>',
      '#suffix' => '</strong>',
      '#weight' => -100,
    ];

    $form['submit'] = [
      '#type' => 'submit',
      '#value' => t('Delete'),
    ];
  }
}
